TalentElevate/Controllers/ApplyCVController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalentElevate.Models;

namespace TalentElevate.Controllers
{
    public class ApplyCVController : Controller
    {
        TalentElevateEntities dbobj = new TalentElevateEntities();

        // GET: ApplyCV
        public ActionResult ApplyCV_Load(int cid, int jid)
        {
            var model = new ApplyCVClass
            {
                company_id = cid, // Update property names to match model
                job_id = jid
            };
            return View(model);
        }

        public ActionResult Apply_click(ApplyCVClass clsobj, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                int cid = clsobj.company_id;
                int jid = clsobj.job_id;

                // Get the job's last date
                DateTime jobLastDate = GetJobLastDate(jid);

                // Check if the current date is after the job's last date
                if (DateTime.Now.Date > jobLastDate)
                {
                    clsobj.msg = "Cannot apply as the job application period has ended.";
                    return View("ApplyCV_Load", clsobj); // Ensure we pass the model
                }

                // Handle file upload
                if (file != null && file.ContentLength > 0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/resu"), filename);
                    file.SaveAs(path);

                    // Set resume path
                    var fullpath = Path.Combine("~\\resu", filename);
                    clsobj.resume = fullpath;
                }

                int uid = Convert.ToInt32(Session["uid"]);
                string status = "Applied";

                // Call stored procedure to insert application
                dbobj.sp_apply(uid, jid, clsobj.resume, DateTime.Now.Date, status);

                clsobj.msg = "Application submitted successfully.";
            }

            return View("ApplyCV_Load", clsobj); // Ensure we pass the model
        }

        private DateTime GetJobLastDate(int jobId)
        {
            var job = dbobj.jobs_tb.FirstOrDefault(j => j.job_id == jobId);
            if (job != null)
            {
                return job.last_date;
            }
            throw new Exception("Job not found.");
        }

    }
}

TalentElevate/Controllers/JobViewController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalentElevate.Models;
using System.Configuration;

namespace TalentElevate.Controllers
{
    public class JobViewController : Controller
    {
        TalentElevateEntities dbobj = new TalentElevateEntities();
        // GET: JobView
        public ActionResult searchjob_Pageload()
        {
            return View(GetData());
        }
        private JobSearch GetData()
        {
            var joblist = new JobSearch();
            List<string> lst = new List<string>();
            var job = dbobj.jobs_tb.ToList();
            foreach (var e in job)
            {
                var jobcls = new UserJobViewClass();
                jobcls.company_id = e.company_id;
                jobcls.job_id = e.job_id;
                jobcls.job_title = e.job_title;
                jobcls.job_description = e.job_description;
                jobcls.job_type = e.job_type;
                jobcls.vacancy = e.vacancy;
                jobcls.salary = e.salary;
                jobcls.skilset = e.skillset;
                jobcls.experience = e.experiance;
                jobcls.location = e.location;
                jobcls.status = e.status;
                jobcls.date = e.last_date;

                joblist.selectjob.Add(jobcls);

                var s = jobcls.skilset;
                lst.Add(s);
                TempData["ski"] = string.Join(" ", lst);
            }
            return joblist;
        }
        public ActionResult searchjob_click(JobSearch clsobj)
        {
            string qry = "";
            string experience = (clsobj.insertse.experience).ToString();
            if (!string.IsNullOrWhiteSpace(experience))
            {
                qry += " and experiance like '%" + clsobj.insertse.experience + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.skilset))
            {
                qry += " and skillset like '%" + clsobj.insertse.skilset + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.job_type))
            {
                qry += " and job_type like '%" + clsobj.insertse.job_type + "%'";
            }
            return View("searchjob_Pageload", getdata1(clsobj, qry));
        }
        private JobSearch getdata1(JobSearch clsobj,string qry)
        {
            using (var con = new SqlConnection(ConfigurationManager.ConnectionStrings["test"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_jobsearch", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                    con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new JobSearch();
                while (dr.Read())
                {
                    var jobcls = new UserJobViewClass();
                    jobcls.company_id = Convert.ToInt32(dr["company_id"].ToString());
                    jobcls.job_title = dr["job_title"].ToString();
                    jobcls.job_description = dr["job_description"].ToString();
                    jobcls.job_type = dr["job_type"].ToString();
                    jobcls.vacancy = Convert.ToInt32(dr["vacancy"].ToString());
                    jobcls.salary = Convert.ToInt32(dr["salary"].ToString());
                    jobcls.skilset = dr["skillset"].ToString();
                    jobcls.experience = Convert.ToInt32(dr["experiance"].ToString());
                    jobcls.location = dr["location"].ToString();
                    jobcls.status = dr["status"].ToString();
                    jobcls.date = Convert.ToDateTime(dr["last_date"]);

                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }
    }
}

TalentElevate/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalentElevate.Models;
namespace TalentElevate.Controllers
{
    
    public class LoginController : Controller
    {
        TalentElevateEntities dbobj = new TalentElevateEntities();
        // GET: Login
        public ActionResult Login_Pageload()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult CompanyHome()
        {
            return View();
        }
        public ActionResult LoginClick(LoginCredentialClass clsobj)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_loginCred(clsobj.username, clsobj.password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    var uid = dbobj.sp_login_id(clsobj.username, clsobj.password).FirstOrDefault();
                    Session["uid"] = uid;

                    var lt = dbobj.sp_login_type(clsobj.username, clsobj.password).FirstOrDefault();
                    if (lt == "user")
                    {
                        return RedirectToAction("UserHome");
                    }
                    else if (lt == "company")
                    {
                        return RedirectToAction("CompanyHome");
                    }
                }
                else
                {
                    ModelState.Clear();
                    clsobj.msg = "Invalid Credentials";
                    return View("Login_Pageload", clsobj);
                }
            }
            return View("Login_Pageload", clsobj);
        }
    }
}

TalentElevate/Views/JobView/searchjob_Pageload.cshtml
@model TalentElevate.Models.JobSearch
@{
    ViewBag.Title = "searchjob_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Job Search</h2>

<div>
    @using (Html.BeginForm("searchjob_click", "JobView", FormMethod.Post))
            {
                <table>
                    <tr>
                        <td style="padding-left:8px"><label>Skills:</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.skilset)</td>
                        <td style="padding-left:8px"><label>Experience:</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.experience)</td>
                        <td style="padding-left:8px"><label>Type:</label></td>
                        <td>@Html.TextBoxFor(m => m.insertse.job_type)</td>
                        <td><input type="submit" value="Search" /></td>
                    </tr>
                </table>
            }
</div>
<div>
    @using (Html.BeginForm("searchjob_Pageload", "JobView", FormMethod.Get))
            {
                if (Model != null)
                {
                    if (Model.selectjob != null && Model.selectjob.Count != 0)
                    {
    <table class="table">
        <tr>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.insertse.company_id)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.job_title)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.job_description)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.job_type)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.vacancy)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.salary)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.skilset)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.experience)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.location)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.status)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.insertse.date)
            </th>
        </tr>
        @foreach (var item in Model.selectjob)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.company_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.job_title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.job_description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.job_type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.vacancy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.skilset)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.experience)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date)
                </td>
                <td>
                    @Html.ActionLink("Apply Now", "ApplyCV_Load", "ApplyCV", new {cid=item.company_id,jid=item.job_id },null)
                </td>
            </tr>
        }
    </table>
                    }
                    else
                    {
                        <script>
                            alert('no data found');
                        </script>
                    }
                }
            }
    <div>
        @Html.ActionLink("Back to Home", "UserHome", "Login")
    </div>
</div>