TalentElevate/Controllers/UserInsertController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalentElevate.Models;
namespace TalentElevate.Controllers
{
    public class UserInsertController : Controller
    {
        TalentElevateEntities dbobj = new TalentElevateEntities();
        // GET: UserInsert
        public ActionResult Insert_Pageload()
        {
            return View();
        }
        public ActionResult InsertUserClick(UserRegClass clsobj,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if(file.ContentLength > 0)
                {
                    string filenamee = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/PHS");
                    string pa = Path.Combine(s, filenamee);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\PHS", filenamee);
                    clsobj.photo = fullpath;//set
                }
                var getmaxid = dbobj.sp_MAXidLogin().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxid);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }
                //get
                dbobj.sp_user_reg(regid,clsobj.fname,clsobj.lname,clsobj.age,clsobj.gender,clsobj.address,clsobj.email,clsobj.phone,clsobj.qualification,clsobj.experience,clsobj.skills,clsobj.nationality,clsobj.city,clsobj.state,clsobj.pincode,clsobj.photo);
                dbobj.sp_login(regid, clsobj.username, clsobj.password, "user", "active");
                clsobj.usermsg = "Registration Successfull";
                return View("Insert_Pageload",clsobj);
            }
            return View("Insert_Pageload", clsobj);
        }
    }
}

TalentElevate/Views/UserInsert/Insert_Pageload.cshtml
@model TalentElevate.Models.UserRegClass
@{
    ViewBag.Title = "Insert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Registration</h2>
@using (Html.BeginForm("InsertUserClick", "UserInsert", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div><label>First Name:</label></div>
    <div>
        @Html.TextBoxFor(m => m.fname)
        @Html.ValidationMessageFor(m => m.fname)
    </div>

    <div><label>Last Name:</label></div>
    <div>
        @Html.TextBoxFor(m => m.lname)
        @Html.ValidationMessageFor(m => m.lname)
    </div>

    <div><label>Age:</label></div>
    <div>
        @Html.TextBoxFor(m => m.age)
        @Html.ValidationMessageFor(m => m.age)
    </div>

    <div><label>Gender:</label></div>
    <div>
        Male
        @Html.RadioButtonFor(m=>m.gender,"Male")
        Female
        @Html.RadioButtonFor(m=>m.gender,"Female")
    </div>

    <div><label>Address:</label></div>
    <div>
        @Html.TextAreaFor(m => m.address)
        @Html.ValidationMessageFor(m => m.address)
    </div>

    <div><label>Email:</label></div>
    <div>
        @Html.TextBoxFor(m => m.email)
        @Html.ValidationMessageFor(m => m.email)
    </div>

    <div><label>Phone:</label></div>
    <div>
        @Html.TextBoxFor(m => m.phone)
        @Html.ValidationMessageFor(m => m.phone)
    </div>

    <div><label>Qualification:</label></div>
    <div>
        @Html.TextBoxFor(m => m.qualification)
        @Html.ValidationMessageFor(m => m.qualification)
    </div>

    <div><label>Experiance:</label></div>
    <div>
        @Html.TextBoxFor(m => m.experience)
        @Html.ValidationMessageFor(m => m.experience)
    </div>

    <div><label>Skills:</label></div>
    <div>
        @Html.TextBoxFor(m => m.skills)
        @Html.ValidationMessageFor(m => m.skills)
    </div>

    <div><label>Nationality:</label></div>
    <div>
        @Html.TextBoxFor(m => m.nationality)
        @Html.ValidationMessageFor(m => m.nationality)
    </div>

    <div><label>City:</label></div>
    <div>
        @Html.TextBoxFor(m => m.city)
        @Html.ValidationMessageFor(m => m.city)
    </div>

    <div><label>State:</label></div>
    <div>
        @Html.TextBoxFor(m => m.state)
        @Html.ValidationMessageFor(m => m.state)
    </div>

    <div><label>Pincode:</label></div>
    <div>
        @Html.TextBoxFor(m => m.pincode)
        @Html.ValidationMessageFor(m => m.pincode)
    </div>

    <div><label>Photo:</label></div>
    <div>
        @Html.TextBox("file","", new { Type = "file" })
        @*@Html.ValidationMessageFor(m => m.photo)*@
    </div>

    <div><label>Username:</label></div>
    <div>
        @Html.TextBoxFor(m => m.username)
        @Html.ValidationMessageFor(m => m.username)
    </div>

    <div><label>Password:</label></div>
    <div>
        @Html.TextBoxFor(m => m.password)
        @Html.ValidationMessageFor(m => m.password)
    </div>

    <div><label>Confirm Password:</label></div>
    <div>
        @Html.TextBoxFor(m => m.confirmpassword)
        @Html.ValidationMessageFor(m => m.confirmpassword)
    </div>

    <div>
        <input type="submit" value="Register"/>
        @Html.DisplayFor(m=>m.usermsg)
    </div>
}